services:
  frontend:
    build:
      context: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  database:
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=post'
      - 'POSTGRES_PASSWORD=secret'
volumes:
  db-data: