services:
  frontend:
    image: 'node:alpine'
    build:
      context: frontend
    ports:
      - "5173:5173"
  database:
    image: 'postgres:15.2'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=post'
      - 'POSTGRES_PASSWORD=secret'
